### ISSUE TITLE
stuck in set-temp

### ISSUE THREAD

**Issue by ThomDietrich** [braveheuel/hm-prowee#1]
Hey ;)
As you already mentioned, your script currently freezes after set-temp. There are error messages in the `homegear.err` file:

```
  RPC Server (Port 2002): Error: Broken pipe
```

Maybe that's because you are not setting all MASTER parameters?

**Comment by braveheuel** [comment]
Hello,

for now I didn't debug this issues. I saw the "broken pipe" as well in my logs, but it seems, that there is something going wrong in the rpc.client communication.

In not settings all MASTER parameters I don't see an issue. I have seen only a problem when setting the TEMPERATURE and the according ENDTIME in two RPC calls. But that was solved in 0f4815e.

I hope I will find some time to debug this issue a little bit more!
