### ISSUE TITLE
new settings not present on device display

### ISSUE THREAD

**Issue by ThomDietrich** [braveheuel/hm-prowee#2]
Hey (again),
after "set-temp" the new temperatures seem to be programmed and I check them via "print-config" but they are not shown on the HM-CC-RT-DN display as little bars, nor are they used. What am I missing?

**Comment by braveheuel** [comment]
Hello again :-)

When the temperatures are seen by "print-config", then it is the "problem" of homegear to send it to the HM-CC-RT-DN device. What does the homegear log say? Also: Can you provide the sample data you tried to send to the device?

**Comment by ThomDietrich** [comment]
just cleaning up. This was back then a hardware defect on my side.
